@api = http://localhost:4000/decano

###Creacion de Nueva Carrera
POST {{api}}/newCarrera
Content-Type: application/json

{
    "nombreMalla":"Medicina",
    "idDecano":1
}
###Creacion de Nueva semestre   
POST {{api}}/newSemestre
Content-Type: application/json

{
    "nombreMalla":"Medicina",
    "nombreSemestre":"PrimerSemestre"
}
###Creacion de Nueva Materia  
POST {{api}}/newMateria
Content-Type: application/json

{
    "nombreMateria":"Algebra II",
    "idSemestre":3,
    "codigo":"10P-H",
    "horasTeoricas":100,
    "horasPracticas":100,
    "creditos":200,
    "requisito":"Algebra I",
    "costo":100
}
####Borrar una materia
DELETE {{api}}/materia/5
