@api = http://localhost:4000/estudiantes

###Consulta de estudiante
GET {{api}}/3

###Consulta de decano
GET {{api}}/decano/1

###Crear un nuevo Estudiante
POST {{api}}
Content-Type: application/json

{
    "nombre":"Sharon",
    "apellido":"Cortes",
    "CI":9172908,
    "idMalla":1,
    "idUsuario":8
}
###Crear un nuevo Decano
POST {{api}}/decano
Content-Type: application/json

{
    "nombre":"Fabian",
    "apellido":"Cortes",
    "CI":9172909,    
    "idUsuario":8
}
###Consultar carreras
GET {{api}}/carreras

###Consultar materias de estudiante
GET {{api}}/materia/1

###Asignar Materia
POST {{api}}/materia
Content-Type: application/json

{
    "idMateria":1,
    "idEstudiante":7,
    "status":"cursando"
}
###nueva nota
POST {{api}}/nota
Content-Type: application/json

{
    "nota":20,
    "idMateria":1,
    "idEstudiante":1,
    "nombreNota":"Prueba"
    
}

###consulta de notas
POST {{api}}/notas
Content-Type: application/json

{
    "idMateria":1,
    "idEstudiante":1
}

###delete nota
DELETE {{api}}/nota/3
###put Update STATUS
PUT {{api}}/nota
Content-Type: application/json

{
    "idMateria":2,
    "idEstudiante":2,
    "status":"reprobado"
}
###Prueba
GET {{api}}/materia/reprobadas/26
###
GET {{api}}/materia/aprobadas/26
###
GET {{api}}/materias/5